version: '3'

services: 
  app:
    build: 
      context: node
    container_name: app 
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - fullCycleNetwork
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db


  db:
    image: mysql:5.7 
    command: --innodb-use-native-aio=0
    restart: always 
    tty: true 
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullCycleNetwork

networks:
  fullCycleNetwork:
    driver: bridge