version: '3'

services: 
  webserver:
    build: 
      context: nginx
    container_name: webserver
    networks:
      - fullCycleNetwork
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    command: node index.js
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - fullCycleNetwork
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7 
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always 
    tty: true 
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullCycleNetwork

networks:
  fullCycleNetwork:
    driver: bridge