version: '3'

services: 
  db:
    image: mysql:5.7 
    command: --innodb-use-native-aio=0
    restart: always 
    tty: true 
    volumes: 
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullCycleNetwork

networks:
  fullCycleNetwork:
    driver: bridge